### ISSUE TITLE
Blockquote erases formatting?

### ISSUE THREAD

**Issue by maxkrieger** [flutter/flutter_markdown#172]
Not sure if it's just me, but with the following code (material theme):

```
md.MarkdownBody(
  data: content,
  onTapLink: this.onClickLink,
  fitContent: true,
  shrinkWrap: false,
  selectable: true,
  styleSheet: md.MarkdownStyleSheet(
       blockquotePadding: EdgeInsets.fromLTRB(10.0, 0, 0, 0),
       blockquoteDecoration: BoxDecoration(
       border:  Border(left: BorderSide(width: 2.0))),
                       code: TextStyle(
                        fontFamily: "Source Code Pro"))
);
```

If `content = "> **hello there**"`, the resulting text is blockquoted, but not bolded. Contrast with standard GitHub flavored markdown behavior:

```
> **hello there**
```
renders as:

> **hello there**

Does this have to do with the parser not parsing children recursively?

**Comment by KagurazakaHanabi** [comment]
https://github.com/flutter/flutter_markdown/blob/6c3a699f730e90308b716ff0d52962fff1cab745/lib/src/builder.dart#L216

Should be `styleSheet.blockquote.merge(_inlines.last.style)` ?

**Comment by KagurazakaHanabi** [comment]
https://github.com/flutter/flutter_markdown/blob/6c3a699f730e90308b716ff0d52962fff1cab745/lib/src/builder.dart#L216

Should be `styleSheet.blockquote.merge(_inlines.last.style)` ?

**Comment by maxkrieger** [comment]
@KagurazakaHanabi would that fix the above example?

**Comment by bierbaumtim** [comment]
#209 brings a fix for this issue. Could you please check if the issue still exists?

**Comment by maxkrieger** [comment]
@bierbaumtim I'm unfortunately pretty low bandwidth at the moment -- if it fixes the code snippet I posted above, feel free to close.

**Comment by djfishe** [comment]
As far as I can tell this issue is still present in v0.5.2. 
The following text is rendered as you can see on the screenshot.
The source:
```
this is a link: [Markdown guide](https://www.markdownguide.org) and this is **bold** and *italic*
> this is a link: [Markdown guide](https://www.markdownguide.org) and this is **bold** and *italic*
````
Screenshot of the rendered result:
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-01-26 at 10 45 53](https://user-images.githubusercontent.com/3807749/105828959-0cecb400-5fc4-11eb-9ecf-46fab4b6207e.png)

**Comment by bierbaumtim** [comment]
@djfishe I will look at it next week.

**Comment by bierbaumtim** [comment]
After a closer look, i realized that my first comment, that he issue is fixed was wrong. I was commenting on the wrong issue. So sorry for the confusion.
The fix for the formatting issues is the one that @KagurazakaHanabi mentioned. Next I will add some tests to be sure that it works and then open a PR.

**Comment by domesticmouse** [comment]
Closed by https://github.com/flutter/flutter_markdown/pull/334

**Comment by djfishe** [comment]
Thanks guys :)
