### ISSUE TITLE
OnTapLink Not working

### ISSUE THREAD

**Issue by sirily11** [flutter/flutter_markdown#191]
Issues: When selectable = true, the onTapLink function will never be triggered.
However, after make selectable = false, everything works fine.

**Comment by AyushBherwani1998** [comment]
That's the known issue for wrapping `GestureDetector` around `SelectableText` or `SelectableText.rich`.  
You can find the issue here: [#40424](https://github.com/flutter/flutter/issues/40424).

Since we are already using `SelectableText.rich` we can use the `onTap` instead of `GestureDetector`.

I would like to work on this issue.

**Comment by sirily11** [comment]
> That's the known issue for wrapping `GestureDetector` around `SelectableText` or `SelectableText.rich`.
> You can find the issue here: [#40424](https://github.com/flutter/flutter/issues/40424).
> 
> Since we are already using `SelectableText.rich` we can use the `onTap` instead of `GestureDetector`.
> 
> I would like to work on this issue.

thanks.
