### ISSUE TITLE
nested lists being garbling

### ISSUE THREAD

**Issue by namiwang** [flutter/flutter_markdown#2]
re-pro:

say the markdown string being:
```
markdown demo

- list
- list
  - list
    - list
  - list
- list demo

```

and the result is:

![flutter_01](https://cloud.githubusercontent.com/assets/1160688/26828756/650fc600-4af5-11e7-97e8-0cab4c880256.png)

**Comment by DaveShuckerow** [comment]
Thanks for filing this issue.  It appears to be fixed in the current version of Flutter markdown:

![image](https://user-images.githubusercontent.com/14947366/36703523-d7ccb0ae-1b10-11e8-9dbd-96a4c1ac5b53.png)

Feel free to file again if you're still having trouble and we can help figure out what's up.
