### ISSUE TITLE
Does it support Emoji

### ISSUE THREAD

**Issue by cilere** [flutter/flutter_markdown#225]
Hello,

I try to use emoji code like: `:bowtie:` in the markdown source, but it just returns me the exactly `:bowtie:` text. 

But if I directly copy the emoji from somewhere like this 😄, it will be emoji.

So, just want to know do you plan to support the emoji code in the future?

**Comment by domesticmouse** [comment]
Emoji code is not documented in the [GitHub Flavoured Markdown](https://github.github.com/gfm/) specification at all. 

At this point the answer is that there is no concrete plan to add support for emoji text, but I will happily review Pull Requests that add support for it.

Thanks!

**Comment by mjordan56** [comment]
The flutter_markdown package does support parsing inline emoji tags. The flutter_markdown package builds on the [markdown package](pub.dev/packages/markdown), which allows users of the Markdown and MarkdownBody widgets to specify extension sets to be used by the markdown parser. Extension sets define a list of block and inline syntax handlers for the parser.

The markdown package defines an inline emoji syntax class for handling emoji characters. The markdown package supports the over 1500 emojis defined by the data file https://github.com/muan/emojilib/raw/master/emojis.json. (FYI, There isn't a bowtie emoji in the set, but I wasn't able to find a bowtie emoji in several of the emoji sets I checked including the Unicode Full Emoji List, v13.0).

To include emoji support in your markdown widget, import the markdown package, and instantiate an ExtensionSet object with an EmojiSyntax object. (here's a minimal code snippet)

```
import 'package:markdown/markdown.dart' as md;

Markdown(
    controller: controller,
    selectable: true,
    data: 'Insert emoji :smiley: here',
    extensionSet: md.ExtensionSet([], [md.EmojiSyntax()]),
)
```
The markdown package has four pre-defined extension sets; ExtensionSet.none, ExtensionSet.commonMark, ExtensionSet.gitHubFlavored, and ExtensionSet.gitHubWeb. The gitHubWeb extension set renders Markdown similarly to GitHub and includes the inline EmojiSyntax. To use this extension set, specify the ExtensionSet.gitHubWeb as the Markdown widget extension set like this:

```
Markdown(
    controller: controller,
    selectable: true,
    data: 'Insert emoji :smiley: here',
    extensionSet: md.ExtensionSet.gitHubWeb,
)

```

**Comment by walsha2** [comment]
@mjordan56 Thanks for that example on the predefined `extensionSet` options, that worked like you showed above.

One issue I ran into is that `md.ExtensionSet.gitHubWeb` does not seem to render some pretty basic emojis using expected **keywords**. For example :

```
:thumbsup: 
:thumbsdown:
```

They obviously do render in Github web and are part of the set linked above.

:thumbsup: 
:thumbsdown:

I poked through the code and found this file `emojis.dart` in the `markdown-2.1.5` package that notes the following, just as you showed above where the source emojis come from:

```dart
// GENERATED FILE. DO NOT EDIT.
//
// This file was generated from emojilib's emoji data file:
// https://github.com/muan/emojilib/raw/master/emojis.json
// at 2019-03-26 11:56:22.016973 by the script, tool/update_emojis.dart.
```

In the source https://github.com/muan/emojilib/raw/master/emojis.json it contains:

```dart
  "+1": {
    "keywords": ["thumbsup", "yes", "awesome", "good", "agree", "accept", "cool", "hand", "like"],
    "char": "👍",
    "fitzpatrick_scale": true,
    "category": "people"
  },
  "-1": {
    "keywords": ["thumbsdown", "no", "dislike", "hand"],
    "char": "👎",
    "fitzpatrick_scale": true,
    "category": "people"
  },
```

But in `emojis.dart` it only contains:

```
  '+1': '👍',
  '-1': '👎',
```

So it looks like `+1` and `-1` are needed and the **keywords are not parsed or considered**. Not sure if that is expected, but just something I ran into that I found odd because it obviously does work it Github web.

**Comment by walsha2** [comment]
Follow up, so I found a personal solution that works for my needs and is quick. I created an extended example of `mb.EmojiSyntax` and it can be found in the following file:

https://gist.github.com/walsha2/d2b835dabbca2a4f0f87492251e5d9ef

The file above also contains a copy of the `emojis.dart` `Map` so users can extend it with any custom keywords or mappings they want to enable. 

Copy this file in your project, add whatever keywords you want (in the example above I added `:thumbsup:` and `:thumbsdown:`), and then use it in `Markdown` widget (as opposed to `md.EmojiSyntax()`):

```dart
Markdown(
    controller: controller,
    selectable: true,
    data: 'Insert emoji :thumbsup: here',
    extensionSet: md.ExtensionSet([], [EmojiSyntaxKeyword()]),
)
```

**Comment by mjordan56** [comment]
@walsha2 I'm glad you found my comment to celiri helpful for finding a solution for your needs. I agree that your solution is completely valid. If it solves your needs then it's a viable solution. Personally, I try not to duplicate code whenever possible. Duplicating the emojis map and the inline emoji syntax parser is something I prefer to avoid. After reflecting on your solution I came up with a solution for your consideration. I created a new class that extends the emoji syntax class like this:

```
class ExtendedEmojiSyntax extends md.EmojiSyntax {
  static const alternateTags = <String, String>{
    'thumbsup': '👍',
    'thumbsdown': '👎',
  };

  @override
  bool onMatch(md.InlineParser parser, Match match) {
    var emoji = alternateTags[match[1]];
    if (emoji != null) {
      parser.addNode(md.Text(emoji));
      return true;
    }
    return super.onMatch(parser, match);
  }
}
```

Then you can include the subclassed extended emoji syntax parser as you did in your example:

```
Markdown(
    controller: controller,
    selectable: true,
    data: 'Insert emoji :thumbsup: here',
      extensionSet: md.ExtensionSet(
        md.ExtensionSet.gitHubWeb.blockSyntaxes,
        <md.InlineSyntax>[
          // Place custom emoji syntax BEFORE gitHubWeb default inlineSyntaxes
          ExtendedEmojiSyntax(),
          ...md.ExtensionSet.gitHubWeb.inlineSyntaxes,
        ],
      ),
)
```

The subclassed extended emoji syntax parser will get a first crack at inserting an emoji. If it doesn't have one then it passes it on to allow the inherited parent to try to find an emoji match. I like this approach because if there are changes, fixes, or enhancements to the parent emoji syntax class the code will still get them.

**Comment by walsha2** [comment]
@mjordan56 that is perfect. Yes, totally agree - avoid code duplication. I have updated my comment above to point to your post. Thanks!

**Comment by domesticmouse** [comment]
Closing out, thanks all!
