### ISSUE TITLE
Video Support

### ISSUE THREAD

**Issue by HasanEltantawy** [flutter/flutter_markdown#252]
How to add video ?

**Comment by mjordan56** [comment]
@HasanEltantawy Embedded video element support is not included in any of the Markdown specifications. If you Google "markdown video" you'll find there is quite a bit of interest in embedding video and audio into a Markdown generated document. They all agree that doing so is not a standard feature of Markdown. Since it isn't an included feature of Markdown there are numerous "_tricks or techniques_" for embedding video or audio content using HTML. All of these approaches have their own advantages and disadvantages. The HTML tricks won't work with the flutter_markdown package as it doesn't support embedded HTML.

If you need to support video elements specified in a Markdown document and plan on using the flutter_markdown package, you'll need to create a custom syntax, most likely a block syntax, and a builder to create the appropriate Flutter widgets to display and play the video.

**Comment by mjordan56** [comment]
@domesticmouse @HasanEltantawy's question has been answered. This issue can be closed.

**Comment by domesticmouse** [comment]
Thanks @mjordan56
