### ISSUE TITLE
Data with more than 4 spaces at the beginning has a weird behavior

### ISSUE THREAD

**Issue by rqton** [flutter/flutter_markdown#273]
Hello,

Since my upgrading from **0.4.3** to **0.4.4** i found a unexpected behavior.
If my data starts with 4 or more spaces, the whole line seems interpreted as a code line.

This bug shows only since v0.4.4

Thanks for your help.

**Comment by mjordan56** [comment]
@rqton can you provide more information about the unexpected behavior you're seeing with a Markdown source text example? I tried this with both 0.4.3 and 0.4.4 and both versions correctly interpret lines of text indented with four or more spaces as being indented code blocks. This is the expected behavior as specified in section 4.4 Indented code blocks in both the [CommonMark](https://spec.commonmark.org/0.29/#indented-code-blocks) and [GitHub Flavored Markdown](https://github.github.com/gfm/#indented-code-blocks) specifications. Please explain why you believe this is unexpected behavior.

**Comment by rqton** [comment]
hey @mjordan56 , ok my bad, you are right, it's in Markdown specs.
However, in 0.4.3, i can start my data with more than 4 spaces without code block interpretation.
Nevermind, thanks for you help, i close this issue !
