### ISSUE TITLE
ImageBuilder inserts unwanted padding

### ISSUE THREAD

**Issue by SwissCheese5** [flutter/flutter_markdown#300]
![image](https://user-images.githubusercontent.com/7407478/99247978-7015d980-2810-11eb-91a6-4b49ba67d10a.png)
![image](https://user-images.githubusercontent.com/7407478/99248440-1d88ed00-2811-11eb-9970-b4987477ad37.png)

There is not supposed to be a space between the two images at all.

```dart
MarkdownBody(
        data: body,
        selectable: selectable,
        extensionSet: md.ExtensionSet(
            md.ExtensionSet.gitHubFlavored.blockSyntaxes,
            List<md.InlineSyntax>.from(subFonts.map((style) => FontSyntax(fonts.indexOf(style))).toList())
              ..addAll(md.ExtensionSet.gitHubFlavored.inlineSyntaxes)),
        builders: {
          'font': FontBuilder(),
        },
        imageBuilder: (src, title, alt) => Container(
            color: Colors.blue,
            width: MediaQuery.of(context).size.width,
            height: 100) //ImageBuilder(uri: src.toString()),
        );
```

**Comment by mjordan56** [comment]
@SwissCheese5 The flutter_markdown package inserts vertical space between Markdown block elements. This vertical space between block elements is uniform between all Markdown block elements; text blocks, tables, headers, etc. You can set the vertical space value in the MarkdownStyleSheet with the blockSpacing parameter. I would hazard to guess that setting this value to zero is not what you want as this will stack all block elements together with no space between them. This should give you the results you desire for your two images but probably isn't what you want for the rest of your Markdown data. You might be able to use multiple Markdown widgets in your layout, separating your images into a separate widget just for your images.

/cc: @domesticmouse This isn't a bug and is expected behavior in the current implementation.

**Comment by domesticmouse** [comment]
Thanks @mjordan56
