### ISSUE TITLE
How do I get an extra line rendered between blocks?

### ISSUE THREAD

**Issue by ksilz** [flutter/flutter_markdown#309]
I want to have an extra line between a list item and the next section:

![image](https://user-images.githubusercontent.com/1061209/101773607-edb5c800-3ae4-11eb-9354-210e788d04fe.png)

So here's my markdown:
```
# Section One
## Subsection
- A list item
  
# Section Two
```

Is there something I can put after `- A list item` to insert a new line? From what I read in #261, "Blank lines between block-level elements are ignored". So there seems to be no official way of doing this. And I can't use the `<br/>` workaround.

So, how do I get an extra line between a list item and the next section?

**Comment by nooralibutt** [comment]
@ksilz I have implemented a workaround on this:

I added `# 1` in my text file and in code I added these lines

`MarkdownBody(
                  data: myText,
                  styleSheet: MarkdownStyleSheet(
                    p: Theme.of(context).textTheme.bodyText1,
                    h1: TextStyle(color: AppTheme.scaffoldBackgroundColor),
                  ),
                ),`

I applied same scaffold color to 1 so 1 will not be visible to user.

**Comment by ksilz** [comment]
@nooralibutt Great suggestion! I use `h1`-`h3` in my markdown, so I picked `h4` as my "heading spacer".

I got two improvements in my version: 
```
h4: TextStyle(color: Colors.transparent, height: 2)
```
- With `Colors.transparent`, this "heading spacer" becomes invisible no matter your color selection, dark mode/light mode and them.
- With `height: 2`, you can define **how** much empty space you get. Play around with it. It's defined as "The height of this text span, as a multiple of the font size."

**Comment by nooralibutt** [comment]
WOW! Amazing. You are genius my friend. Thanks for sharing this. :)

**Comment by mjordan56** [comment]
@ksilz and @nooralibutt It looks like you've both found a suitable workaround that works for your situation. Additional horizontal layout control is a bit of a sore point with Markdown users. ksilz, as you correctly referenced #261, the Markdown specs don't provide a solution for inserting blank lines into the output. If your workaround solution becomes unworkable, you could define a custom block element to insert vertical space in your formatted output. You could define a tag like "{br:12}" or something similar to stand for a 12 unit line break. You'd have to create a BlockSyntax class to pass to the Markdown parser and a MarkdownElementBuilder to inject an appropriate widget. Your workaround is much simpler but I thought you might be interested in other solutions.

@domesticmouse Brett, I think this issue can be closed since ksilz and nooralibutt have a workaround solution that appears to work for their needs.

**Comment by domesticmouse** [comment]
Thanks again @mjordan56

**Comment by ksilz** [comment]
@mjordan56, @domesticmouse Thank you! Yes, I'm happy with my workaround. Case closed!

**Comment by capntrips** [comment]
I ended up here trying to find how to inject custom widgets, and I couldn't find any example of that or how to use `BlockSyntax` with a `MarkdownElementBuilder`, so here's how I managed to get the above to work:

```dart
class BreakSyntax extends md.BlockSyntax {
  @override
  RegExp get pattern => RegExp(r'^\{br:(\d+(?:\.\d+)?)\}$');

  @override
  md.Node parse(md.BlockParser parser) {
    final match = pattern.firstMatch(parser.current);
    parser.advance();
    return md.Element('pre', [md.Element.text('break', match.group(1))]);
  }
}

class BreakBuilder extends MarkdownElementBuilder {
  @override
  Widget visitElementAfter(md.Element element, TextStyle preferredStyle) {
    return Container(
        height:double.parse(element.textContent),
        width: 0
    );
  }
}
```
Fractional height is probably overkill, but `Container` required a double, so I just added it to the regex. A width of 0 was required to prevent a full width white block, and `Colors.transparent` didn't hide it.

To use it, add the `Builder` and `ExtensionSet` to your `Markdown` widget:

```dart
MarkdownBody(
  data: markdownString,
  builders: {'break': BreakBuilder()},
  extensionSet: md.ExtensionSet([BreakSyntax()], []),
)
```
