### ISSUE TITLE
Problematic asserts made in style_sheet.dart

### ISSUE THREAD

**Issue by carlleeswanson** [flutter/flutter_markdown#319]
There are currently two asserts in flutter_markdown/src/style_sheet.dart that appear unnecessary and problematic. One is for Material and one is for Cupertino. Both test to see that fontSize for the theme is non-null. This seems inappropriate. Shouldn't they simply use the default values (as provided in text_style.dart)? 

The asserts are:
> 79:   assert(theme?.textTheme?.bodyText2?.fontSize != null);

and
> 138:  assert(theme?.textTheme?.textStyle?.fontSize != null);

Can these be removed in the next release?

**Comment by iapicca** [comment]
@carlleeswanson  
[flutter_markdown](https://pub.dev/packages/flutter_markdown) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/flutter/flutter_markdown/issues)

**Comment by domesticmouse** [comment]
Thoughts @mjordan56?

**Comment by mjordan56** [comment]
@domesticmouse I took a look at the asserts @carlleeswanson has identified as problematic. In reviewing the code, I can understand why the asserts were added. They're in place to help identify potentially bad cases of trying to instantiate a Markdown style sheet without the appropriate prerequisite data. Let's look at each assert individually since they are two distinct cases:

### First assert in `MarkdownStyleSheet.fromTheme`

This assert was added on Sept 29, 2017, with PR #5 by @tvolkert. This assert is the only code change in the package code along with a block of test code. This assert was added due to some bug or other problem @tvolkert identified and decided an assert was needed. If the `theme.textTheme.bodyText2` is `null`, an exception will be thrown when the font size of the `code` theme is defined. I investigated @carlleeswanson's suggestion of using a default value, but there isn't any default value. Font sizes in the text_style.dart are all defined a being nullable. The only default font size defined in text_style.dart is in the `getParagraphStyle` method. There is a `getTextStyle` method, but it returns null for the font size if a font size hasn't been explicitly set.

The only suggestion I have regarding this assert is the observation that there multiple text themes in the MarkdownStyleSheet.fromTheme constructor that can be null. I assume the assert was added to avoid an exception being thrown when calculating the `code` text style's font size. Since other text themes in the MarkdownStyleSheet can also be null, set the `code` text theme to null when `theme.textTheme.bodyText2` is `null` and `code` font size to `null` when the bodyText2 is null.

### Second assert in `MarkdownStyleSheet.fromCupertinoTheme`

This assert was added on Nov 24, 2019, with PR #99 by @bierbaumtim. The assert was introduced along with the `MarkdownStyleSheet.fromCupertinoTheme`. The assert is trying to protect the font size calculations in the `code` and the first five header types. As with the previous case, there is not text size default to fall back on.

Looking closer at these two constructors, there are lots of null safety issues. Text themes, text styles, etc. are all nullable.

My recommendation is to leave the asserts in place unless @carlleeswanson can demonstrate why they are problematic. Please explain or show cases where these asserts cause problems. When would creating a Markdown style sheet be valid when the font sizes being checked are null?

**Comment by domesticmouse** [comment]
Closing out
