### ISSUE TITLE
Dart 2 incompatibilities

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter_markdown#53]
Dart SDK constraint needs to be raised to accept 2.0 stable:
https://github.com/flutter/flutter_markdown/blob/master/pubspec.yaml#L21

Analysis is not passing:
```
15.12s$ flutter test
Running "flutter packages get" in flutter_markdown...        5.2s
00:07 +0: loading /home/travis/build/flutter/flutter_markdown/test/flutter_markdown_test.dart                                                                                                          compiler message: file:///home/travis/.pub-cache/hosted/pub.dartlang.org/mockito-3.0.0-beta+1/lib/src/call_pair.dart:32:22: Error: The class 'TypeMatcher' is abstract and can't be instantiated.
compiler message:       : call = const TypeMatcher<Invocation>();
compiler message:                      ^^^^^^^^^^^
compiler message: file:///home/travis/.pub-cache/hosted/pub.dartlang.org/mockito-3.0.0-beta+1/lib/src/call_pair.dart:1: Error: Cannot invoke a non-'const' constructor where a const expression is expected.
compiler message: Try using a constructor or factory that is 'const'.
compiler message: file:///home/travis/.pub-cache/hosted/pub.dartlang.org/mockito-3.0.0-beta+1/lib/src/call_pair.dart:32:22: Error: Too few positional arguments: 1 required, 0 given.
compiler message:       : call = const TypeMatcher<Invocation>();
```

**Comment by gamebox** [comment]
Seems that this issue is fixed in mockito at https://github.com/dart-lang/mockito/issues/156.
Don't have time to put a PR together right now, but i could on Sunday.

**Comment by mit-mit** [comment]
That would be fantastic!

**Comment by gamebox** [comment]
Seems like the problem goes deeper than that:

`Because mockito >=3.0.0-beta+3 depends on test ^1.2.0 and every version of flutter_test from sdk depends on test 0.12.37, mockito >=3.0.0-beta+3 is incompatible with flutter_test from sdk.`

This is discussed in https://github.com/flutter/flutter/issues/20011

So as I see it there are a couple options if we want to support Dart 2 and therefore Flutter as it is largely used:

1. Find a way to remove `mockito` as a dependency. This seems to be non-trivial to do if we want to replace it.  An option is to only test FileImages in the test suite until flutter_test's `test` dependency updates to ^1.2.0.  I don't know if that's an acceptable compromise though. 
2. Work upstream to update flutter_test's dependency on test from 0.12.37 to ^1.2.0 or better so that the version solver can do it's job.  There seems to be a lot of work to update this though as the pubspec for `flutter_test` warns people to tread lightly around updating due to relying on some rather specific behavior in that version of `test`.

Let me know what you think is the best course of action.  If we decide on the FileImage compromise of option 1, I can work up a PR for that pretty quickly.

**Comment by mit-mit** [comment]
cc @Hixie can you advice?

**Comment by Hixie** [comment]
See https://github.com/dart-lang/matcher/pull/88 and https://github.com/flutter/flutter/issues/18608.
